### ISSUE TITLE
Broken! Enabling Breaks Gear Wheel Menu

### ISSUE THREAD

**Issue by hifihedgehog** [MonDiscourse/discourse-strikethrough#1]
See video:

https://github.com/MonDiscourse/discourse-strikethrough/assets/16614343/482cb6eb-c6c8-4c49-8cb6-854a2e5ed764

**Comment by MonDiscourse** [comment]
The issue is kinda the same as the other. You shouldn't have Formatting toolbar plugin and these buttons. They have the same buttons and it will break the composer.

The formatting toolbar plugin has a strikethrough button already so this component is useless to you.

The strikethrough component on its own works fine

![image](https://github.com/MonDiscourse/discourse-strikethrough/assets/95508132/a07cffa8-cb45-45a7-8ea5-28511dec8ccd)
